-- Auto-generated from schema-map-postgres.yaml (map@74ce4f4)
-- engine: postgres
-- table:  hash_profiles

CREATE TABLE IF NOT EXISTS hash_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  algo_id BIGINT NOT NULL,                    -- crypto_algorithms (class='hash'), e.g. SHA3-512
  output_len SMALLINT NULL,                   -- in bytes; NULL = full length
  params JSONB NULL,                          -- e.g. { "peppered": true, "context": "email", "domain_sep": "app:v1" }
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT uq_hash_profiles UNIQUE (name),
  CONSTRAINT chk_hp_status CHECK (status IN ('active','deprecated'))
);
